### ISSUE TITLE
All in one solution to deploy prometheus/grafana/storj-exporter in docker

### ISSUE THREAD

**Issue by anclrii** [anclrii/Storj-Exporter#11]

**Comment by Cmdrd** [comment]
Might also not be a terrible idea to look into including Prometheus AlertManager into this setup so that people can get email notifications on certain events such as long time since last ping or audit failure levels reaching a certain level. Saves them having to be keeping an eye on the dashboard all the time or if they are away for a while and possibly catching a problem before it becomes a major issue such as node disqualification.
If there is enough interest and once we have everything mapped into the exporter as possible and any other pressing additions or improvements, I can start looking into that. I will likely end up implementing it myself anyway but depending on interest can re-prioritize as needed.

**Comment by angelsantillana94** [comment]
finally, did you work on this solution?

**Comment by anclrii** [comment]
Added a docker-compose example here https://github.com/anclrii/Storj-Exporter-dashboard/tree/master/quick_start
Need to add links to this repo readme now
